name: Delete File

on:
  workflow_dispatch: # 允许手动触发

jobs:
  delete-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete file
        run: |
          git rm update.yml
          git commit -m "Delete update.yml"
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
