name: Update xConfig

on:
  schedule:
    - cron: '5 16 * * *'
    - cron: '5 4 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pyyaml

      - name: Get current date (Beijing Time)
        id: date
        run: |
          echo "CURRENT_DATE=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Fetch data and update output.yaml
        id: fetch-content
        run: |
          python xConfig/update.py

      - name: Send email on no changes or failure
        if: ${{ failure() || steps.fetch-content.outputs.FETCH_ERROR == 'true' || steps.fetch-content.outputs.HAS_CHANGES == 'false' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "xConfig更新出错 ${{ env.CURRENT_DATE }}"
          body: |
            工作流运行状态：
            - 脚本版本: 1.1
            - 动态 URL: ${{ steps.fetch-content.outputs.DYNAMIC_URL }}
            - 日志链接: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            - 状态: ${{ steps.fetch-content.outputs.FETCH_ERROR == 'true' && '动态 URL 无法访问' || steps.fetch-content.outputs.HAS_CHANGES == 'false' && '内容未发生变化，无需更新' || '工作流运行失败' }}
          to: lyqnihao@163.com
          from: ${{ secrets.EMAIL_USERNAME }}
          content_type: text/plain

      - name: Commit and push changes
        if: steps.fetch-content.outputs.HAS_CHANGES == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add xConfig/output.yaml
          git commit -m "Automatically update output.yaml"
          git push
